[font]
size = 12.0

[font.bold]
family = "SauceCodePro NFM"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro NFM"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro NFM"
style = "Italic"

[font.normal]
family = "SauceCodePro NFM"
style = "Regular"

[shell]
program = "/usr/bin/zsh"
